### ISSUE TITLE
Error at .deserialize when inserting to table

### ISSUE THREAD

**Issue by kysely** [michaelwittig/node-q#39] opened 2018-08-21 21:25 UTC
Hello @michaelwittig ,

I'm experiencing weird difficulties with simple table insertions.

I can create a new table and run queries on it without a problem, but always get weird deserialisation error when trying to insert a record to the table.

It feels to me like the backtick (`) in the first position is the problem. Here's a toy example:

```js
    coll.con.k('progress:([]gender:`symbol$();weight:`long$())', err => {
	if (err) throw err
	console.log('created new table')

	coll.con.k("`progress insert (`male, 91)", (err, res) => {
	    if (err) throw err
	    console.log('wrote new record', res)
	})

    })
```

The error I get points to [this if statement](https://github.com/michaelwittig/node-q/blob/master/lib/c.js#L326), but I don't really understand its context.

```
Error: progress insert (`male, 91)
    at r (/Users/radek/Documents/Work/PROJECTS/spotter/node_modules/node-q/lib/c.js:327:10)
    at Object.deserialize (/Users/radek/Documents/Work/PROJECTS/spotter/node_modules/node-q/lib/c.js:402:9)
    at Socket.<anonymous> (/Users/radek/Documents/Work/PROJECTS/spotter/node_modules/node-q/index.js:55:15)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
```

I don't know it it's just the way error messages got printed, but it misses the backtick in the first position.

Obviously, if you put the string
```q
`progress insert (`male, 91)
```

to the `q` console itself, it inserts the record.

Can you please help? Am I doing something wrong? 

Thank you :)

**Comment by michaelwittig** [comment] 2018-08-22 11:09
I can confirm that
```
coll.con.k("`progress insert (`male, 91)", (err, res) => {
```
does not work

while this works:
```
coll.con.k("insert[`progress;(`male, 91)]", (err, res) => {
```

The problem is that `node-q` serialises a JavaScript string as a symbol if it starts with a `
and `progress;(`male, 91)]` is not a valid symbol :)

Fix is coming shortly

**Comment by michaelwittig** [comment] 2018-08-22 11:10
fixed in `node-q@2.4.2`

**Closed** 2018-08-22 11:09 UTC

**Comment by kysely** [comment] 2018-08-22 13:27
Thank you very much for the library and this fix ❤️

**Comment by kysely** [comment] 2018-08-22 13:35
Can I donate somewhere?

**Comment by kysely** [comment] 2018-08-22 17:35
Yes, thank you :)
